CREATE TABLE COPY_EMP AS 
SELECT * FROM EMPLOYEE;

---- 사원 번호 시퀀스 생성
--CREATE SEQUENCE SEQ_EMPNO
--START WITH 223
--INCREMENT BY 1
--NOCACHE
--NOCYCLE;

--SELECT * FROM COPY_EMP WHERE EMP_ID = '224';
--
--DROP SEQUENCE SEQ_EMPNO;
--
--GRANT SELECT, INSERT, UPDATE ON COPY_EMP TO KH;



SELECT * FROM COPY_EMP WHERE EMP_NAME = '김현지';
