-- 오라클 KH계정
-- 이클립스 99_JDBC_Homework

-- EMPLOYEE 테이블 서브쿼리로 복제하여 
--COPY_EMP 테이블 생성 및 사원번호로 활용할 시퀀스(SEQ_EMPNO) 생성
CREATE TABLE COPY_EMP AS 
SELECT * FROM EMPLOYEE;

---- 사원 번호 시퀀스 생성
--CREATE SEQUENCE SEQ_EMPNO
--START WITH 223
--INCREMENT BY 1
--NOCACHE
--NOCYCLE;

--SELECT * FROM COPY_EMP WHERE EMP_ID = '224';
--
--DROP SEQUENCE SEQ_EMPNO;



SELECT * FROM COPY_EMP WHERE EMP_NAME = '김현지';

SELECT * FROM COPY_EMP;



DROP TABLE COPY_EMP;
DROP SEQUENCE SEQ_EMPNO;

CREATE TABLE COPY_EMP 
AS SELECT * FROM EMPLOYEE;

SELECT * FROM COPY_EMP;

CREATE SEQUENCE SEQ_EMPNO;


INSERT INTO COPY_EMP
VALUES(SEQ_EMPNO.NEXTVAL, '김현지', '920909-1111111', 'hj@kh.or.kr', '01012341234', 'D9', 'J1', 'S1', 5000000, 0.1, '200', '25-01-15', NULL, 'N');


UPDATE COPY_EMP 
SET EMAIL = ?, PHONE = ?, SALARY = ?, WHERE EMP_ID = ?"