DROP TABLE BOOK;
CREATE TABLE BOOK;
SELECT * FROM BOOK;

CREATE TABLE BOOK(
    BNO NUMBER PRIMARY KEY, -- 컬럼 레벨 방식
    TITLE VARCHAR2(30), 
    AUTHOR VARCHAR2(20) NOT NULL,
    PUBLISHER VARCHAR2(20) NOT NULL,
    PRICE NUMBER, 
    DESCRIPTION VARCHAR2(30)
    );

INSERT INTO BOOK VALUES(100, '잃어버린 성훈이를 찾아서', '');




CREATE TABLE MAGAZINE
AS SELECT * FROM BOOK;

DROP TABLE MAGAZINE;
CREATE TABLE MAGAZINE;
SELECT * FROM MAGAZINE;

CREATE TABLE MAGAZINE(
    BNO NUMBER , -- 컬럼 레벨 방식
    TITLE VARCHAR2(30), 
    AUTHOR VARCHAR2(20) NOT NULL,
    PUBLISHER VARCHAR2(20) NOT NULL,
    PRICE NUMBER, 
    DESCRIPTION VARCHAR2(30)
    );